// Theme registry. Add a new theme by appending an object to THEMES.
// Each theme defines a complete color system; applyTheme() maps these to
// design tokens (T.*) and CSS custom properties on :root.
export const THEMES = [
  {
    id: 'rosa-palo',
    name: 'Rosa Palo',
    description: 'Cálido, femenino, suave',
    colors: {
      primary:          '#d4688a',
      primaryText:      '#ffffff',
      background:       '#fff8f9',
      sidebar:          '#fdf0f3',
      sidebarText:      '#6b2d45',
      sidebarTextMuted: '#b07a90',
      surface:          '#ffffff',
      surfaceHover:     '#fff0f4',
      border:           '#f5c6d8',
      text:             '#3d1a27',
      textMuted:        '#9e6070',
    },
    font: 'Nunito',
  },
  {
    id: 'lavanda-pro',
    name: 'Lavanda Pro',
    description: 'Elegante, calmo, moderno',
    colors: {
      primary:          '#7c5cbf',
      primaryText:      '#ffffff',
      background:       '#f7f5ff',
      sidebar:          '#f0ecff',
      sidebarText:      '#3b1f7a',
      sidebarTextMuted: '#8b72c8',
      surface:          '#ffffff',
      surfaceHover:     '#f3f0ff',
      border:           '#ddd6fe',
      text:             '#2d1f4a',
      textMuted:        '#7c6b9e',
    },
    font: 'Nunito',
  },
  {
    id: 'verde-salud',
    name: 'Verde Salud',
    description: 'Clínico, sereno (default)',
    colors: {
      primary:          '#2f4a3a',
      primaryText:      '#ffffff',
      background:       '#f8faf9',
      sidebar:          '#1e3329',
      sidebarText:      '#e8f5ee',
      sidebarTextMuted: '#7aab8a',
      surface:          '#ffffff',
      surfaceHover:     '#f2f8f4',
      border:           '#d1e8d9',
      text:             '#1a2e22',
      textMuted:        '#5a7a65',
    },
    font: 'Inter',
  },
  {
    id: 'oceano',
    name: 'Océano',
    description: 'Moderno, corporativo',
    colors: {
      primary:          '#0077b6',
      primaryText:      '#ffffff',
      background:       '#f4f8fc',
      sidebar:          '#023e8a',
      sidebarText:      '#e0f0ff',
      sidebarTextMuted: '#6aafd6',
      surface:          '#ffffff',
      surfaceHover:     '#eef5fc',
      border:           '#bde0fe',
      text:             '#012a4a',
      textMuted:        '#4a7fa0',
    },
    font: 'Inter',
  },
  {
    id: 'carbon',
    name: 'Carbón',
    description: 'Oscuro, alto contraste',
    colors: {
      primary:          '#818cf8',
      primaryText:      '#0f0f14',
      background:       '#16161e',
      sidebar:          '#0f0f14',
      sidebarText:      '#e8e8f0',
      sidebarTextMuted: '#6b6b80',
      surface:          '#1e1e2a',
      surfaceHover:     '#252535',
      border:           '#2a2a3a',
      text:             '#e8e8f0',
      textMuted:        '#8888a0',
    },
    font: 'Inter',
  },
  {
    id: 'ultra-pro',
    name: 'Ultra Pro',
    description: 'Minimal, blanco y negro',
    colors: {
      primary:          '#111827',
      primaryText:      '#ffffff',
      background:       '#f9fafb',
      sidebar:          '#111827',
      sidebarText:      '#f3f4f6',
      sidebarTextMuted: '#9ca3af',
      surface:          '#ffffff',
      surfaceHover:     '#f3f4f6',
      border:           '#e5e7eb',
      text:             '#111827',
      textMuted:        '#6b7280',
    },
    font: 'DM Sans',
  },
]

export const DEFAULT_THEME_ID = 'verde-salud'
export const getTheme = (id) => THEMES.find(t => t.id === id) ?? THEMES.find(t => t.id === DEFAULT_THEME_ID)
